version: '2'
services:
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - jenkins:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
volumes:
  jenkins:
