version: '2'
services:
  jenkins:
    build: 
      context: .
      dockerfile: JenkinsDockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $(which docker):/usr/bin/docker
      - jenkins:/var/lib/jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
