version: '2'
services:
  jenkinsdata:
    build: jenkins-data
  jenkinsmaster:
    build: jenkins-master
    volumes_from:
      - jenkinsdata
    ports:
      - '50000:50000'
    restart: always
  nginx:
    command: '/run.sh'
    build: nginx
    ports:
       - '80:80'
       - '443:443'
    links:
       - jenkinsmaster:jenkins-master
       - portainer:portainer
    volumes_from:
      - mycv
    restart: always
  jenkinsnodeslave:
    build: jenkins-node-slave
  mycv:
    image: didelotkev/my_cv
  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
