version: '2'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    command: "--smallfiles --logpath=/dev/null"
  webapp:
    build:
      context: ../../
      dockerfile: ./docker/webapp/Dockerfile
    environment:
      NODE_ENV: production
    command: npm start
    ports:
      - "4000:4000"
    links:
      - db
