version: '3.6'

volumes:
  portainer_data:

networks:
  ingress_network:
    external: true

services:
  portainer:
    image: portainer/portainer
    command:
      - '--host=unix:///var/run/docker.sock'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer_data:/data
    networks:
      - ingress_network
    ports:
      - 9000:9000
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
