version: '3.6'

configs:
  prometheus_config:
    file: prometheus/prometheus.yml
  grafana_datasources_config:
    file: grafana/provisioning/datasources/all.yml
  grafana_dashboards_config:
    file: grafana/provisioning/dashboards/all.yml
  grafana_dashboard_prometheus_config:
    file: grafana/provisioning/dashboards/prometheus-stats_rev1.json
  grafana_dashboard_swarm_config:
    file: grafana/provisioning/dashboards/docker-swarm-monitor_rev1.json
  nginx_global_config:
    file: nginx/conf/nginx.conf
  nginx_grafana_config:
    file: nginx/conf/grafana.conf
  nginx_jenkins_config:
    file: nginx/conf/jenkins.conf
  nginx_mycv_config:
    file: nginx/conf/mycv.conf
  nginx_portainer_config:
    file: nginx/conf/portainer.conf

secrets:
  docker_tls_cert_ca:
    file: certs/ca.pem
  docker_tls_cert_cert:
    file: certs/cert.pem
  docker_tls_cert_key:
    file: certs/key.pem
  GRAFANA_USER:
    external: true
  GRAFANA_PASSWORD:
    external: true
  JENKINS_USER:
    external: true
  JENKINS_PASSWORD:
    external: true

volumes:
  jenkins_data:
  jenkins_logs:
  mycv_logs:
  portainer_data:
  grafana_logs:
  grafana_data:
  prometheus_data:
  mycv:
  nginx_logs:
  nginx_certificates:

networks:
  services_network:
    driver: overlay

services:
  haproxy:
    image: dockercloud/haproxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - nginx
    networks:
      - services_network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        preferences:
          - spread: node.labels.haproxy
        constraints:
          - node.role == manager
          - node.labels.haproxy == true

  jenkinsmaster:
    image: 0.0.0.0:5000/jenkins_master
    build: jenkins-master
    secrets:
      - docker_tls_cert_ca
      - docker_tls_cert_cert
      - docker_tls_cert_key
    volumes:
      - jenkins_logs:/var/log/jenkins
      - jenkins_data:/var/jenkins_home
    secrets:
      - JENKINS_USER
      - JENKINS_PASSWORD
    networks:
      - services_network
    deploy:
      restart_policy:
        condition: on-failure

  mycv:
    image: didelotkev/my_cv
    volumes:
      - mycv_logs:/var/log/nginx
    networks:
      - services_network
    deploy:
      restart_policy:
        condition: on-failure

  portainer:
    image: portainer/portainer
    command:
      - '--host=unix:///var/run/docker.sock'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - services_network
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

# MONITORING
  grafana:
    image: 0.0.0.0:5000/grafana
    build: grafana
    configs:
      - source: grafana_datasources_config
        target: /etc/grafana/provisioning/datasources/all.yml

      - source: grafana_dashboards_config
        target: /etc/grafana/provisioning/dashboards/all.yml

      - source: grafana_dashboard_prometheus_config
        target: /etc/grafana/provisioning/dashboards/prometheus-stats_rev1.json

      - source: grafana_dashboard_swarm_config
        target: /etc/grafana/provisioning/dashboards/docker-swarm-monitor_rev1.json
    secrets:
      - GRAFANA_USER
      - GRAFANA_PASSWORD
#    volumes:
#      - grafana_logs:/var/log/grafana
#      - grafana_data:/var/lib/grafana
    networks:
      - services_network
    deploy:
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus:v2.0.0
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    depends_on:
      - cadvisor
    networks:
      - services_network
    deploy:
      restart_policy:
        condition: on-failure

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - services_network
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - services_network
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  nginx:
    image: 0.0.0.0:5000/nginx_proxy
    build: nginx
    environment:
      - SERVICE_PORTS=80,443
    configs:
      - source: nginx_global_config
        target: /etc/nginx/nginx.conf

      - source: nginx_grafana_config
        target: /etc/nginx/conf.d/grafana.conf

      - source: nginx_jenkins_config
        target: /etc/nginx/conf.d/jenkins.conf

      - source: nginx_mycv_config
        target: /etc/nginx/conf.d/mycv.conf

      - source: nginx_portainer_config
        target: /etc/nginx/conf.d/portainer.conf
    volumes:
      - nginx_logs:/var/log/nginx
      - nginx_certificates:/etc/letsencrypt
    networks:
      - services_network
    depends_on:
      - jenkinsmaster
      - mycv
      - portainer
      - grafana
    deploy:
      restart_policy:
        condition: on-failure
