---
########## DOCKER SWARM SERVICES ##########

- hosts: manager1
  become: yes
  tasks:
#    - name: Tag the manager as the node for hosting the registry.
#      command: docker node update --label-add registry=true {{ ansible_hostname }}

#    - name: Tag the manager as the entrypoint for nginx proxy
#      shell: docker node update --label-add entrypoint=true {{ ansible_hostname }}

# Check if registry already started
    - name: Check if the registry service is already started
      command: docker service ls | grep registry
      register: is_registry_started

    - name: Run the registry as a service
      command: |
        docker service create \
          --name registry \
#          --constraint 'node.labels.registry==true' \
          --publish published=5000,target=5000 \
          --replicas 1 \
          registry:2
      when: not is_registry_started

    - name: Build manager docker compose (nginx, jenkins, grafana, mycv, portainer).
      make:
        chdir: "/home/{{ ansible_user }}/docker/managers"
        target: build
      tags: docker_services
