---
########## CONTROLLER PLAYBOOK ##########
#
# Deploy:
#   - Jenkins
#   - Grafana
#   - Gitlab
#

- hosts: controllers
  remote_user: "{{ admin_user }}"
  become: yes
  vars:
    docker_tls_certs_path: "/etc/ssl/certs/docker"
    jenkins_master_docker_path: "/home/{{ admin_user }}/docker/controller/jenkins-master"
    pip_install_packages:
      - name: docker-py
  roles:
    - role: pip

    - role: docker-daemon-certificate
      dds_host: "{{ ansible_host }}"
      dds_country: "FR"
      dds_state: "France"
      dds_locality: "Paris"
      dds_organization: "DidelotCorp"
      dds_client_cert_path: "{{ docker_tls_certs_path }}"

    - role: docker
      docker_users:
        - "{{ admin_user }}"
      docker_daemon_options:
        hosts:
          - "unix:///var/run/docker.sock"
          - "tcp://{{ ansible_host }}:2376"
        tlsverify: true
        tlscacert: "{{ dds_server_cert_path }}/ca.pem"
        tlscert: "{{ dds_server_cert_path }}/server-cert.pem"
        tlskey: "{{ dds_server_cert_path }}/server-key.pem"
  post_tasks:
    - name: Install docker compose.
      pip:
        name: docker-compose
        state: present

    - name: Copy docker to remote.
      copy:
        src: ../docker
        dest: "/home/{{ admin_user }}"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: 0644
        force: yes

    - name: Copy local certificates to jenkins master image before build.
      copy:
        src: "{{ docker_tls_certs_path }}/{{ item }}"
        dest: "{{ jenkins_master_docker_path }}/certs/{{ item }}"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: 0644
        remote_src: yes
      with_items:
        - ca.pem
        - cert.pem
        - key.pem

    - name: Start controller docker compose (nginx, jenkins).
      docker_service:
        project_src: "/home/{{ admin_user }}/docker/controller"
        project_name: controller
        build: yes
