---
########## CONTROLLER PLAYBOOK ##########
#
# Deploy:
#   - Jenkins
#   - Grafana
#   - Gitlab
#

- hosts: controllers
  remote_user: "{{ admin_user }}"
  become: yes
  vars:
    docker_tls_certs_path: "/etc/ssl/certs/docker"
    jenkins_master_docker_path: "/home/{{ admin_user }}/docker/controller/jenkins-master"
    jenkins_node_slave_docker_path: "/home/{{ admin_user }}/docker/controller/jenkins-node-slave"
    docker_list_to_add_certs:
      - "{{ jenkins_master_docker_path }}"
      - "{{ jenkins_node_slave_docker_path }}"
    certs_list:
      - ca.pem
      - cert.pem
      - key.pem
    pip_install_packages:
      - name: docker-py
  roles:
    - role: pip

    - role: docker-daemon-certificate
      dds_host: "{{ ansible_host }}"
      dds_country: "FR"
      dds_state: "France"
      dds_locality: "Paris"
      dds_organization: "DidelotCorp"
      dds_client_cert_path: "{{ docker_tls_certs_path }}"

    - role: docker
      docker_users:
        - "{{ admin_user }}"
      docker_daemon_options:
        hosts:
          - "unix:///var/run/docker.sock"
          - "tcp://{{ ansible_host }}:2376"
        tlsverify: true
        tlscacert: "{{ dds_server_cert_path }}/ca.pem"
        tlscert: "{{ dds_server_cert_path }}/server-cert.pem"
        tlskey: "{{ dds_server_cert_path }}/server-key.pem"
  post_tasks:
    - name: Install docker compose.
      pip:
        name: docker-compose
        state: present

    - name: Copy docker to remote.
      copy:
        src: ../docker
        dest: "/home/{{ admin_user }}"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: 0644
        force: yes

    - name: Copy certificates to the folders of docker images that will use tcp to connect to host daemon.
      copy:
        src: "{{ docker_tls_certs_path }}/{{ item.1 }}"
        dest: "{{ item.0 }}/certs/{{ item.1 }}"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: 0644
        remote_src: yes
      with_nested:
        - "{{ docker_list_to_add_certs }}"
        - "{{ certs_list }}"

    - name: Start controller docker compose (nginx, jenkins).
      docker_service:
        project_src: "/home/{{ admin_user }}/docker/controller"
        project_name: controller
        build: yes
