---
########## CONTROLLER PLAYBOOK ##########
#
# Deploy:
#   - Jenkins
#   - Grafana
#   - Gitlab
#

- hosts: controller
  remote_user: "{{ admin_user }}"
  become: yes
  vars:
    jenkins_port: 3000
    jenkins_slaves_port: 50000
    pip_install_packages:
      - name: docker-py

  roles:
    - role: pip

    - role: docker
      docker_install_compose: true
      docker_compose_version: "1.15.0"
      docker_compose_path: /usr/local/bin/docker-compose

    - role: nginx
      nginx_vhosts:
        - listen: "80"
          server_name: "jenkins.didelotkev.ovh"
          extra_parameters: |
            location / {
                proxy_pass http://localhost:3000/;
            }
        - listen: "80"
          server_name: "grafana.didelotkev.ovh"
          extra_parameters: |
            location / {
                proxy_pass http://localhost:4000/;
            }
        - listen: "80"
          server_name: "gitlab.didelotkev.ovh"
          extra_parameters: |
            location / {
                proxy_pass http://localhost:5000/;
            }

    - role: jenkins

# Install docker cli in jenkins docker

# Retoune l'id du container docker

# sudo docker logs id_docker_container (To get the first admin password of jenkins)

# docker build -t super_jenkins -f ./JenkinsDockerfile

# sudo ansible-galaxy install -r requirements.yml -p ./roles

# sudo chmod 777 /var/run/docker.sock A mettre dans le dockerfile de jenkins (sinon il ne pourra pas build de docker)

