---
########## CONTROLLER PLAYBOOK ##########
#
# Deploy:
#   - Jenkins
#   - Grafana
#   - Gitlab
#

- hosts: controller
  remote_user: "{{ admin_user }}"
  become: yes
  vars:
    jenkins_port: 3000
    jenkins_slaves_port: 50000
    pip_install_packages:
      - name: docker-py
  roles:
    - role: pip

    - role: docker
      docker_install_compose: true
      docker_compose_version: "1.15.0"
      docker_compose_path: /usr/local/bin/docker-compose
      docker_daemon_options:
        hosts:
          - "unix:///var/run/docker.sock"
          - "tcp://0.0.0.0:2375"

    - role: nginx
      nginx_vhosts:
        - listen: "80"
          server_name: "jenkins.didelotkev.ovh"
          extra_parameters: |
            location / {
                proxy_pass http://localhost:8080/;
            }
        - listen: "80"
          server_name: "grafana.didelotkev.ovh"
          extra_parameters: |
            location / {
                proxy_pass http://localhost:4000/;
            }
        - listen: "80"
          server_name: "gitlab.didelotkev.ovh"
          extra_parameters: |
            location / {
                proxy_pass http://localhost:5000/;
            }

    - role: jenkins
