---
########## INITIALIZATION PLAYBOOK ##########
#
# This playbook initialize all the servers
#

- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Install python 2.
      raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)
    - name: Set default locale.
      lineinfile: dest=/etc/default/locale
        regexp="LC_ALL"
        line="LC_ALL=\"en_US.UTF-8\""
    - name: Update apt.
      apt:
        update_cache: yes

- hosts: all
  remote_user: "{{ default_user }}"
  become: true
  tasks:
    - name: Create new user
      user:
        name: "{{ admin_user }}"
        password: "{{ admin_user_password }}"
        groups: sudo
        shell: /bin/bash
        append: yes

    - name: Set authorized key
      authorized_key:
        user: "{{ admin_user }}"
        state: present
        key: "{{ lookup('file', remote_path_to_admin_user_ssh_key) }}"
