---
########## SITE PLAYBOOK ##########
#
# Prepare webserver to host webapp
#

- hosts: webserver
  remote_user: "{{ admin_user }}"
  become: yes
  roles:
    - role: docker

    - role: nginx
      nginx_vhosts:
        - listen: "80"
          server_name: "webapp.didelotkev.ovh"
          extra_parameters: |
            location / {
                proxy_pass http://localhost:3000/;
            }

    - role: node
