---
########## SITE PLAYBOOK ##########
#
# Prepare webserver to host webapp
#

- hosts: webserver
  remote_user: "{{ admin_user }}"
  become: yes
  roles:
    - docker
    - docker_compose
    - nginx
    - node
