---
- name: Download Debian Source
  get_url:
    url="https://deb.nodesource.com/setup_{{ node_version }}.x"
    dest="/tmp/setup_{{ node_version }}.x"
    mode=0755
  register: debianSource

- name: Install Debian Source
  shell:
    bash /tmp/setup_{{ node_version }}.x
  become: yes
  become_method: sudo
  when: debianSource.changed

- name: Update APT Cache
  apt:
    update_cache=yes
  become: yes
  become_method: sudo
  when: debianSource.changed

- name: Install NodeJS
  apt: pkg=nodejs state=present
  become: yes
  become_method: sudo
