---
vrrp_nic: "eth0"
keepalived_instances:
  internal:
    interface: "{{ vrrp_nic }}"
    state: "{{ (groups['all'].index(inventory_hostname) == 0) | ternary('MASTER','BACKUP') }}"
    virtual_router_id: 42
    priority: "{{ (groups['all']|length - groups['all'].index(inventory_hostname)) * 250 // (groups['all']|length) }}"
    vips:
      - "192.168.50.50/24 dev {{ vrrp_nic }}"
