---
########## DOCKER SWARM SERVICES ##########

- hosts: manager1
  remote_user: "{{ admin_user }}"
  become: yes
  tasks:
    - name: Tag the manager as the node for hosting the registry
      shell: docker node update --label-add registry=true {{ ansible_hostname }}

    - name: Tag the manager as the entrypoin for nginx proxy
      shell: docker node update --label-add entrypoint=true {{ ansible_hostname }}

# Check if registry already started

#    - name: Run the registry as a service
#      shell: |
#        docker service create \
#          --name registry \
#          --constraint 'node.labels.registry==true' \
#          --publish published=5000,target=5000 \
#          --replicas 1 \
#          registry:2

    - name: Build manager docker compose (nginx, jenkins, grafana, mycv, portainer).
      make:
        chdir: "/home/{{ admin_user }}/docker/managers"
        target: build
      tags: docker_services
