---
########## MAIN PLAYBOOK ##########
#
# This playbook assures that on the server
# all the project dependencies are installed
#
#

- hosts: webservers
  remote_user: superuser
  become: yes
  roles:
    - docker
    - franklinkim.docker-compose
#    - role: nginx
#      nginx_http_params:
#        sendfile: &quot;on&quot;
#        access_log: &quot;/var/log/nginx/access.log&quot;
#      nginx_sites:
#       - server:
#          file_name: foo
#          listen: 8080
#          server_name: jenkins
#          root: &quot;/tmp/site1&quot;
#          location1: {name: /, try_files: &quot;$uri $uri/ /index.html&quot;}
#       - server:
#          file_name: bar
#          listen: 3000
#          server_name: webapp
#          root: &quot;/tmp/site2&quot;
#          location1: {name: /, try_files: &quot;$uri $uri/ /index.html&quot;}

# todo install and config nginx

# Install docker cli in jenkins docker

# Retoune l'id du container docker

# sudo docker logs id_docker_container (To get the first admin password of jenkins)

# docker build -t super_jenkins -f ./JenkinsDockerfile

# sudo ansible-galaxy install -r requirements.yml -p ./roles

# sudo chmod 777 /var/run/docker.sock A mettre dans le dockerfile de jenkins (sinon il ne pourra pas build de docker)

