---
########## PLAYBOOK ##########

- name: Create new user
  hosts: webservers
  remote_user: ubuntu
  become: yes
  roles:
    - user

- name: Delete default user
  hosts: webservers
  remote_user: superuser
  become: yes
  tasks:
    - shell : "killall -KILL -u ubuntu; userdel -fr ubuntu"
  ignore_errors: yes